### PR TITLE
Frontend - added grunt build process

### PR DESCRIPTION
**Pull request by fidel-karsto**
This change is [Reviewable](https://reviewable.io/reviews/manuelkasiske/mutservice/24)

### CODE REVIEW

**Comment by j-musca** [comment]
Reviewed 2 of 51 files at r1.
Review status: 2 of 48 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[docker-compose.yml, line 1 \[r1\]](https://reviewable.io:443/reviews/manuelkasiske/mutservice/24#-KFnOsFUCNYwiVzeNhc5:-KFnOsFUCNYwiVzeNhc6:-1106200122) ([raw file](https://github.com/manuelkasiske/mutservice/blob/30d63decc41904ca284d8052a02abdf11de4c71f/docker-compose.yml#L1)):*
Wird diese Datei irgenwo benutzt?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/manuelkasiske/mutservice/24)*

**Comment by j-musca** [comment]
Reviewed 3 of 51 files at r1.
Review status: 5 of 48 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[mutservice.go, line 85 \[r1\]](https://reviewable.io:443/reviews/manuelkasiske/mutservice/24#-KFnPBYEqJrpSxzvALZV:-KFnPBYF5VFE21hNlq2X:-24348727) ([raw file](https://github.com/manuelkasiske/mutservice/blob/30d63decc41904ca284d8052a02abdf11de4c71f/mutservice.go#L85)):*
what is the benefit of /json/ ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/manuelkasiske/mutservice/24)*

**Comment by j-musca** [comment]
Reviewed 24 of 51 files at r1.
Review status: 29 of 48 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/manuelkasiske/mutservice/24)*

**Comment by j-musca** [comment]
Reviewed 22 of 51 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/manuelkasiske/mutservice/24)*

**Comment by fidel-karsto** [comment]
Review status: 44 of 48 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[docker-compose.yml, line 1 \[r1\]](https://reviewable.io:443/reviews/manuelkasiske/mutservice/24#-KFnOsFUCNYwiVzeNhc5:-KFns-_GXimBKrUayWES:-1624074818) ([raw file](https://github.com/manuelkasiske/mutservice/blob/30d63decc41904ca284d8052a02abdf11de4c71f/docker-compose.yml#L1)):*
stimmt -  ist ja nun durch das Dockerfile hinfällig geworden! :) Ich lösche sie.

---

*[mutservice.go, line 85 \[r1\]](https://reviewable.io:443/reviews/manuelkasiske/mutservice/24#-KFnPBYEqJrpSxzvALZV:-KFnsGhnIpZNkvV2h-MK:-1155839219) ([raw file](https://github.com/manuelkasiske/mutservice/blob/30d63decc41904ca284d8052a02abdf11de4c71f/mutservice.go#L85)):*
In my opinion it is more clear what to expect as response by prefixing the REST url accordingly. If we want a different data format in the future (xml, yml, whatever) we already have a url pattern defined and can build on that (e.g. /yml/subscribers).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/manuelkasiske/mutservice/24)*

**Comment by j-musca** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/manuelkasiske/mutservice/24)*

**Comment by manuelkasiske** [comment]
added docker-compose.yml again to make sure that npm install is going to be executed after container has been started with volume.

**Pull request merged**
